### ISSUE TITLE
Feature Request: Visualize results in latex table format that can be added in papers

### ISSUE THREAD

**Issue by IssamLaradji** [haven-ai/haven-ai#2]
The goal is to obtain the results from jupyter and generate them in latex format that can be pasted in a paper

**Comment by RodolfoFerro** [comment]
Do you expect a command that can be run inside a Jupyter cell and it converts the notebook directly to a `.tex` file?

I think that a Pandoc integration can be done for this.

**Comment by IssamLaradji** [comment]
Hi @RodolfoFerro  sorry I wasn't clear.  By running the jupyter dashboard `hj.get_dashboard(rm, vars(), wide_display=True)` it will give us results like these.

![image](https://user-images.githubusercontent.com/3382128/94952101-67ad4d80-04b3-11eb-89ed-dae831573b30.png)

For this `issue`, we are trying to create a `latex` widget like the one below that can visualize these results in latex table format.

![image](https://user-images.githubusercontent.com/3382128/94953917-4dc13a00-04b6-11eb-9aa7-280797f57ea0.png)

So that when they are added to a paper it should look like something like this

![image](https://user-images.githubusercontent.com/3382128/94953982-67fb1800-04b6-11eb-96b2-7f64a6e703d1.png)

This `latex` still needs more testing and extra features be super useful.

In my experience, creating latex tablesy for papers  takes a loong time and is prone to human error. The goal of this is to streamline this process and make it reliable.

**Comment by IssamLaradji** [comment]
it has been added see the latex tab in https://colab.research.google.com/drive/1iqmJWTfsC3Erfay_SwEoUhq_wS4l18Fd#scrollTo=7bCDi3VlFsir
