### ISSUE TITLE
Error when trying to visualize

### ISSUE THREAD

**Issue by ashok-arjun** [haven-ai/haven-ai#25]
Hi!

I am trying to visualize the trained model of [LCFCN](https://github.com/ElementAI/LCFCN ).

I followed your instructions in section 4 after training a model - I specified my directory instead the `<savedir_base>` as instructed.

But I get the error `ValueError: exp_list is empty...` and I am unable to visualise my model and its loss curves etc.

Here is a screenshot that shows my code and the error:
![Screenshot from 2021-03-08 22-38-16](https://user-images.githubusercontent.com/43197536/110355284-10fa0000-805f-11eb-82d9-742b46316eb4.png)

I would really appreciate it if you help me.

Thanks.

**Comment by IssamLaradji** [comment]
are the results in `.results/` ? please set `savedir_base=./results`. The ResultManager will then extract the results from each experiment.

**Comment by ashok-arjun** [comment]
Thanks a ton for your help!
